### ISSUE TITLE
rotated_ship_data is not found

### ISSUE THREAD

**Issue by xing-shuai** [bsridatta/Rotated-Object-Detection#1]
there is no rotated_ship_data.py under src folder

**Comment by bsridatta** [comment]
Hello @xing-shuai, thanks for your interest! 
Yes, unfortunately, this repo does not contain the dataset. I do not have access/rights to the dataset I worked with.
However, to fill in the information gap, the network is made to take an image and perform a 'single rotated object', 'single class' detection. 
The focus of the work is on exploring Modulated Rotated Loss and how it compares to normal L1, L2 losses, how it behaves with other activations functions etc. And also to explore small and efficient architectures.

The idea is to scale it to multiple objects and multi-class to support something like this dataset
https://www.kaggle.com/rhammell/ships-in-satellite-imagery/code
