### ISSUE TITLE
ModuleNotFoundError: No module named 'src.CUDA'

### ISSUE THREAD

**Issue by explorer-xai** [bsridatta/Rotated-Object-Detection#2]
```
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from src.CUDA.ORN.orn.functions import oraligned1d
ModuleNotFoundError: No module named 'src.CUDA'

```

You haven't  uploaded src.CUDA   

Could you please do it?
I am lookinhg forward to run ORN model script, else please let me know the source repo.

**Comment by bsridatta** [comment]
I am sorry if I gave false hope, I have mentioned in the readme that it could be an improvement. And that it's incomplete in the model description. I had some problems integrating it and didn't go further with it. I think there was some issue with the repo itself, can't remember. 

The link is expired but the author now has a re-implementation of it in a new repo which excellent documentation - have fun! https://github.com/ZhouYanzhao/ORN

```class Detector_ORN(nn.Module):
    """Incomplete implementation of Oriented Response Networks, runs only on gpu
    Implicitly learns orientation of objects using ARF(Active Rotation Filters)
    Advatages - better IOU, fewer parameters, faster convergence, should be ideal for the task
    ORN paper - https://arxiv.org/pdf/1701.01833.pdf
    """```
